name: Terraform

on: [push, pull_request]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Set up Go for Terratest
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'  # Specify the Go version compatible with your Terratest

      - name: Run Terratest
        run: |
          cd test
          go mod tidy
          go test -v
